version: "3.9"
services:
  evmos:
    image: ghcr.io/notional-labs/evmos
    deploy:
      replicas: 5
    ports:
      - "26656:26656"
      - "1317:1317"
      - "26657:26657"
      - "8545:8545"
      - "9090:9090"
